- hosts: apt
  become: true
  become_user: root
  tasks:
    - name: update & upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        autoclean: yes
        autoremove: yes
