- hosts: cluster
  become: true
  become_user: root
  tasks:
    - name: standard software packages
      apt:
        pkg:
        - htop
        - sudo
        - nfs-common
        - git
        - boinc-client
        - docker.io
        update_cache: yes
        state: present
    - name: add uwe to docker group
      user:
        name: uwe
        groups: docker,sudo
        append: yes
    - name: start boinc client
      systemd:
        name: boinc-client
        state: started 
        enabled: yes
    - name: register boinc project
      command:
        cmd: "boinccmd --project_attach {{ boinc_url }} {{ boinc_auth }}"
        chdir: /var/lib/boinc
        creates: /var/lib/boinc-client/{{ boinc_file }}